server:
  port: 8082

spring:
  application:
    name: movie-service

  # Corrected PostgreSQL Properties
  datasource:
    username: 'postgres'
    # Use the service name 'postgres' to connect to the container
    url: jdbc:postgresql://postgres:5432/cine_vision
    password: '12345'
    driver-class-name: org.postgresql.Driver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  
  # Corrected Apache Kafka Producer Properties
  kafka:
    producer:
      # Use the service name 'kafka'
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.kaankaplan.movieService.entity.dto.EmailMessageKafkaDto
    topic:
      name: email_topics

  # Corrected Zipkin Properties
  zipkin:
    # Use the service name 'zipkin'
    base-url: http://zipkin:9411
  
  # Sleuth Properties
  sleuth:
    sampler:
      probability: 1.0

# Corrected Eureka Properties
eureka:
  client:
    service-url:
      # Use the service name of your Eureka server
      # The password format is also corrected
      defaultZone: http://admin:admin123@eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Circuit Breaker Properties
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  
    
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s